import {
  AirVent,
  Anchor,
  Award,
  Baby,
  Bath,
  Bed,
  BedDouble,
  Bell,
  Bike,
  Brush,
  Building,
  Building2,
  Bus,
  Calendar,
  Camera,
  Car,
  Check,
  ChefHat,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Crown,
  Disc,
  Dumbbell,
  Eye,
  Flame,
  Gamepad2,
  Gift,
  Globe,
  Hammer,
  Headphones,
  Heart,
  Home,
  Key,
  Lamp,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  Microwave,
  Mountain,
  Music,
  PawPrint,
  Phone,
  Plane,
  Plug,
  Refrigerator,
  Sailboat,
  ShieldCheck,
  ShoppingBag,
  ShowerHead,
  Smile,
  Snowflake,
  Sparkles,
  Speaker,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Tent,
  Train,
  Trees,
  Tv,
  Umbrella,
  Utensils,
  WashingMachine,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Curated lucide icons for villa hospitality. Used by the icon picker
 *  in admin and the icon resolver in `amenity-icons.ts`. */
export const ICON_OPTIONS: Array<{ name: string; Icon: LucideIcon }> = [
  { name: "Wifi", Icon: Wifi },
  { name: "Tv", Icon: Tv },
  { name: "AirVent", Icon: AirVent },
  { name: "Coffee", Icon: Coffee },
  { name: "Wine", Icon: Wine },
  { name: "Utensils", Icon: Utensils },
  { name: "ChefHat", Icon: ChefHat },
  { name: "Refrigerator", Icon: Refrigerator },
  { name: "Microwave", Icon: Microwave },
  { name: "WashingMachine", Icon: WashingMachine },

  { name: "Bath", Icon: Bath },
  { name: "ShowerHead", Icon: ShowerHead },
  { name: "Bed", Icon: Bed },
  { name: "BedDouble", Icon: BedDouble },

  { name: "Waves", Icon: Waves },
  { name: "Umbrella", Icon: Umbrella },
  { name: "Anchor", Icon: Anchor },
  { name: "Sailboat", Icon: Sailboat },

  { name: "Mountain", Icon: Mountain },
  { name: "Trees", Icon: Trees },
  { name: "Sprout", Icon: Sprout },
  { name: "Leaf", Icon: Leaf },
  { name: "Sun", Icon: Sun },
  { name: "Cloud", Icon: Cloud },
  { name: "Sunrise", Icon: Sunrise },
  { name: "Sunset", Icon: Sunset },

  { name: "Flame", Icon: Flame },
  { name: "Snowflake", Icon: Snowflake },
  { name: "Sparkles", Icon: Sparkles },

  { name: "Dumbbell", Icon: Dumbbell },
  { name: "Gamepad2", Icon: Gamepad2 },
  { name: "Music", Icon: Music },
  { name: "Disc", Icon: Disc },
  { name: "Speaker", Icon: Speaker },
  { name: "Headphones", Icon: Headphones },

  { name: "Car", Icon: Car },
  { name: "Bike", Icon: Bike },
  { name: "Plane", Icon: Plane },
  { name: "Train", Icon: Train },
  { name: "Bus", Icon: Bus },

  { name: "ShieldCheck", Icon: ShieldCheck },
  { name: "Camera", Icon: Camera },
  { name: "Zap", Icon: Zap },
  { name: "Lightbulb", Icon: Lightbulb },
  { name: "Plug", Icon: Plug },
  { name: "Lock", Icon: Lock },
  { name: "Key", Icon: Key },
  { name: "Bell", Icon: Bell },

  { name: "PawPrint", Icon: PawPrint },
  { name: "Baby", Icon: Baby },

  { name: "Heart", Icon: Heart },
  { name: "Star", Icon: Star },
  { name: "Crown", Icon: Crown },
  { name: "Award", Icon: Award },

  { name: "Phone", Icon: Phone },
  { name: "MapPin", Icon: MapPin },
  { name: "Calendar", Icon: Calendar },
  { name: "Clock", Icon: Clock },
  { name: "Globe", Icon: Globe },
  { name: "Compass", Icon: Compass },

  { name: "Tent", Icon: Tent },
  { name: "Home", Icon: Home },
  { name: "Building", Icon: Building },
  { name: "Building2", Icon: Building2 },

  { name: "Smile", Icon: Smile },
  { name: "Gift", Icon: Gift },
  { name: "ShoppingBag", Icon: ShoppingBag },
  { name: "Brush", Icon: Brush },
  { name: "Hammer", Icon: Hammer },
  { name: "Wrench", Icon: Wrench },
  { name: "Eye", Icon: Eye },
  { name: "Lamp", Icon: Lamp },
];

/** name → component map for the resolver. */
export const ICON_NAME_TO_COMPONENT: Record<string, LucideIcon> = Object.fromEntries(
  ICON_OPTIONS.map((o) => [o.name, o.Icon]),
);

export function getIconByName(name: string | undefined): LucideIcon {
  if (!name) return Check;
  return ICON_NAME_TO_COMPONENT[name] ?? Check;
}
